### PR TITLE
Adjust for http-client 0.5.*

### PR DESCRIPTION
**Pull request by cdornan**
I think the patch for admitting the latest `http-client{-tls}` and `aeson` should be fairly straightforward.

cc @adamgundry @Mikolaj @markhibberd

### CODE REVIEW

**Comment by cdornan** [comment]
Sorry &mdash; just remembered this needs to conditionalised for backwards compatibility with `http-client` < 0.5.

**Comment by markhibberd** [comment]
If you do that I will merge and push up a release for you tomorrow.

**Comment by cdornan** [comment]
I think it should cover `http-client`<0.5 now.

**Comment by cdornan** [comment]
@markhibberd the original patch was fine in fact as `parseRequest`
constructs a request that will not trap non-2xx HTTP responses,
so it was fine to just use that request.

The backwards compatibility issue is with the use of `parseRequest`
itself, which was introduced in http-client-4.3.0. Before that 
`parseURL` must be used and `checkStatus` overridden.

In testing this on ghc-7.8.4 I realised that for `base` < 4.8 
Applicative would need to be imported into 
`Network.Api.Support.Response` so I have added a
corresponding conditional import.

If you are not concerned with these backwards compatibility issues
then you can use the original patch (though you might want to
tighten the package lower bounds accordingly).

**Comment by markhibberd** [comment]
I think the backwards compat is an improvement, it is much appreciated thanks. I will merge and do a release.

**Comment by markhibberd** [comment]
@cdornan Thanks, there is a release up here - http://hackage.haskell.org/package/network-api-support-0.3.1 - let me know if you run into any issues.

**Pull request merged**
