### PR TITLE
Bounds on aeson and tls loosened to accommodate the latest versions

### PR DESCRIPTION
**Pull request by cdornan**
Looks good for the latest version of `aeson` and `tls`, building fine.

The bounds for version `0.3.1` can be edited directly on Hackage.

### CODE REVIEW

**Comment by markhibberd** [comment]
Will merge and upload when I have a minute later today. Thanks.

**Comment by markhibberd** [comment]
http://hackage.haskell.org/package/network-api-support-0.3.2

**Comment by markhibberd** [comment]
Thanks @cdornan

**Comment by cdornan** [comment]
Cheers

**Pull request merged**
