### PR TITLE
support http-client 0.5

### PR DESCRIPTION
**Pull request by jonpetterbergman**
Support for http-client 0.5 and clean up a deprecation warning.

From version 0.5 of http-client the default is to NOT throw an exception on non-success status codes.

If you would like to continue support for http-client < 0.5 please tell me.

### CODE REVIEW

**Comment by markhibberd** [comment]
@jonpetterbergman If possible it would be good to support the lower http-client bounds, two reasons:
 - there are a few things around that depend on this that use an older version of http-client and I don't think this should be the thing that forces an upgrade unless it really has to 
 - means that the major version doesn't need a bump, which saves me a bit of time

**Comment by jonpetterbergman** [comment]
I'm sketching on a patch for supporting old and new http-client using a
cabal flag.

tisdag 20 september 2016 skrev markhibberd <notifications@github.com>:

**Comment by jonpetterbergman** [comment]
I have a a version now that compiles with http-client 0.4 and 0.5, have not been able to test it with 0.3 or earlier:

https://github.com/jonpetterbergman/network-api-support/tree/http-client-0.5

I also included a version bump for aeson.

**Comment by markhibberd** [comment]
So sorry, I missed notifications on this and it slipped past me. I will incorporate on
A version on hackage this week.

**Comment by markhibberd** [comment]
This is on hackage as 0.2.3, there is also now a 0.3 based on your original patch that drops older support moving forward. Thank you for the effort, and again apologies for dropping this so badly.

**Comment by markhibberd** [comment]
(not I have merged the code to release/0.2.3 and tagged it, there was a small tweak required to build a valid hackage package, it requires the extra source files to be specified out side of the flag for sdist).

**Pull request closed without merging**
